DFR_Blog/DFR_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("blog.urls")),
    path('', TemplateView.as_view(template_name="blog/index.html")),
]

DFR_Blog/blog/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework_swagger.views import get_swagger_view
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from . import views

schema_view = get_schema_view(
    openapi.Info(
        title="Episyche Technologies",
        default_version='v1',),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

app_name = 'blog'

router = routers.DefaultRouter()
router.register(r'posts', views.PostViewSet, basename='post')

urlpatterns = [
    path('', include(router.urls)),
    path('docs/', schema_view.with_ui('swagger',
                                      cache_timeout=0), name='schema-swagger-ui'),

]

DFR_Blog/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 100)
    content = models.TextField()
    author = models.CharField(max_length = 150)
    date_created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title

DFR_Blog/blog/views.py
from rest_framework import viewsets
from .models import Post
from .serializers import PostSerializer
# Create your views here.


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

DFR_Blog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      id="picostrap-styles-css"
      href="https://cdn.livecanvas.com/media/css/library/bundle.css"
      media="all"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/livecanvas-team/ninjabootstrap/dist/css/bootstrap.min.css"
      media="all"
    />
  </head>

  <body>
    <div
      lc-helper="background"
      class="container-fluid py-5 mb-4 d-flex justify-content-center"
      style="
        background-image: url('https://images.unsplash.com/photo-1519681393784-d120267933ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;ixlib=rb-1.2.1&amp;auto=format&amp;fit=crop&amp;w=1124&amp;q=100');
        background-position: center;
        background-size: cover;
        background-repeat: no-repeat;
        height: 100vh;
      "
    >
      <div
        class="p-5 mb-4 lc-block col-xxl-7 col-lg-8 col-12"
        style="
          backdrop-filter: blur(6px) saturate(102%);
          -webkit-backdrop-filter: blur(6px) saturate(102%);
          background-color: rgba(255, 255, 255, 0.45);
          border-radius: 12px;
          border: 1px solid rgba(209, 213, 219, 0.3);
        "
      >
        <div class="lc-block">
          <div editable="rich">
            <h2 class="fw-bolder display-3">Django REST framework</h2>
          </div>
        </div>
        <div class="lc-block col-md-8">
          <div editable="rich">
            <p class="lead">
            Some reasons you might want to use REST framework: 
            <ul>
              <li>The Web browsable API is a huge usability win for your developers.</li>
              <li>Authentication policies including packages for OAuth1a and OAuth2.</li>
              <li>Serialization that supports both ORM and non-ORM data sources.</li>
              <li>Customizable all the way down - just use regular function-based views if you don't need the more powerful features. </li>
              <li>Extensive documentation, and great community support. </li>
              <li>Used and trusted by internationally recognized companies including Mozilla, Red Hat, Heroku, and Eventbrite.</li>
            </ul>
            </p>
          </div>
        </div>
        <div class="lc-block">
          <a class="btn btn-dark" href="{% url 'blog:api-root' %}" role="button"
            >Click me, to view API</a
          >
          <a
            class="btn btn-dark"
            href="{% url 'blog:schema-swagger-ui' %}"
            role="button"
            >Click me, to view DOCS</a
          >
        </div>
      </div>
    </div>

    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>